import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Log Analysis Dashboard", layout="wide")

st.title("📊 Web Server Log Analysis Dashboard")
st.markdown("Upload a parsed CSV log file (generated by `log_parser.py`) to visualize web traffic and identify potential anomalies.")

uploaded_file = st.file_uploader("Upload Parsed Log CSV", type=['csv'])

if uploaded_file is not None:
    # Load data
    df = pd.read_csv(uploaded_file)
    
    # Basic metrics
    total_requests = len(df)
    unique_ips = df['ip'].nunique()
    total_bytes = df['bytes'].sum() / (1024 * 1024) # MB
    
    col1, col2, col3 = st.columns(3)
    col1.metric("Total Requests", total_requests)
    col2.metric("Unique IP Addresses", unique_ips)
    col3.metric("Total Bandwidth (MB)", f"{total_bytes:.2f}")
    
    st.markdown("---")
    
    # Layout for charts
    c1, c2 = st.columns(2)
    
    with c1:
        st.subheader("HTTP Status Codes")
        status_counts = df['status'].value_counts().reset_index()
        status_counts.columns = ['Status Code', 'Count']
        # Treat status as string for categorical coloring
        status_counts['Status Code'] = status_counts['Status Code'].astype(str) 
        
        fig_status = px.pie(status_counts, values='Count', names='Status Code', 
                            title="Distribution of Status Codes", hole=0.3)
        st.plotly_chart(fig_status, use_container_width=True)
        
    with c2:
        st.subheader("Top 10 IP Addresses")
        ip_counts = df['ip'].value_counts().head(10).reset_index()
        ip_counts.columns = ['IP Address', 'Request Count']
        
        fig_ips = px.bar(ip_counts, x='IP Address', y='Request Count', 
                         title="Most Active IP Addresses",
                         labels={'Request Count':'Requests'})
        st.plotly_chart(fig_ips, use_container_width=True)
        
    st.markdown("---")
    
    # Bottom layout
    st.subheader("Requested Paths (Top 15)")
    path_counts = df['path'].value_counts().head(15).reset_index()
    path_counts.columns = ['Path', 'Count']
    
    fig_paths = px.bar(path_counts, x='Count', y='Path', orientation='h',
                       title="Most Frequently Accessed Paths")
    fig_paths.update_layout(yaxis={'categoryorder':'total ascending'})
    st.plotly_chart(fig_paths, use_container_width=True)
    
    st.markdown("---")
    
    st.subheader("Raw Log Data (Preview)")
    st.dataframe(df.head(100))

else:
    st.info("Please upload a CSV file generated by the `log_parser.py` script to begin.")
